# Generated by Django 3.2.8 on 2021-11-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211105_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
